invoker.goals.1 = clean verify -Pjunit3
invoker.goals.2 = clean verify -Pjunit4-old
invoker.goals.3 = clean verify -Pjunit4
invoker.goals.4 = clean verify -Ppojo
invoker.goals.5 = clean verify -Ptestng-old
invoker.goals.6 = clean verify -Ptestng
invoker.goals.7 = clean verify -Pmixed-vintage
invoker.goals.8 = clean verify -Pmixed-providers
invoker.goals.9 = clean verify -Ptestng-groups
invoker.goals.10 = clean verify -Ptestng-suite
invoker.goals.11 = clean verify -Ptestng-suite -Dframework=testng-suite-override -Dtest=TestNGFilteringTest#selected
invoker.goals.12 = clean verify -Ptestng-suite -Dframework=testng-suite-property -Dsurefire.suiteXmlFiles=absent-suite.xml
